[book]
title = "Pegasus for Dummies"
authors = ["Radhakrishna Sanka"]
language = "en"
description = "Open source ecosystem contributor guide for Pegasus ELN. Â© Aegion Dynamic."

[output.html]
git-repository-url = "https://github.com/pegasus-eln/pegasus-for-dummies"
